# Generated by Django 5.2.4 on 2025-07-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150)),
                ('dia_chi', models.CharField(max_length=250)),
                ('ngay_sinh', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phong_ban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_shop.phongban')),
            ],
        ),
    ]
