# Generated by Django 5.2.5 on 2025-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('avatar', models.ImageField(default='images/avatars/noavatar.png', upload_to='images/avatars')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
