# Generated by Django 5.2.5 on 2025-08-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_member_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
